name: Launch dispatch event

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/github-script@v6
        with: 
          github-token: ${{ secrets.ACCESS_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'juanzq10dev',
              repo: 'Python-Password-Generator',
              workflow_id: 'main.yml',
              ref: 'main'
            })
        
