name: Create and run python wheel

on: 
  workflow_call: 
    inputs: 
      wheel-name: 
        required: true
        type: string

jobs: 
  create-and-run-wheel: 
    runs-on: ubuntu-latest

    steps: 
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with: 
        python-version: '3.10'
        
    - name: Build wheel
      run: |
          pip install wheel
          python setup.py bdist_wheel

    - name: Installing wheel 
      run: pip install ./dist/password_generator-1.0-py3-none-any.whl

    - name: Verify that library is correctly installed
      run: python ./test/test.py
      
